### ISSUE TITLE
Remove the Counter component from the project

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#24]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

The project got set up with Svelte, but now that the project is advancing, we no longer need the demo Counter component.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Delete the `src/lib/Counter.svelte` file and remove the Counter component from `src/App.svelte`

```diff
<script lang="ts">
	import svelteLogo from './assets/svelte.svg';
-	import Counter from './lib/Counter.svelte';
</script>

<header>
	<h1>The beginnings of the classic Connect Four game.</h1>
</header>
<main>
	<div>
		<a href="https://vitejs.dev" target="_blank">
			<img src="/vite.svg" class="logo" alt="Vite Logo" />
		</a>
		<a href="https://svelte.dev" target="_blank">
			<img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
		</a>
	</div>
	<h2>Vite + Svelte</h2>

	<div class="card">
-		<Counter />
	</div>

	<p>
		Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank"
			>SvelteKit</a
		>, the official Svelte app framework powered by Vite!
	</p>

	<p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
	h1 {
		padding: 1rem;
		border: 2rem dotted blue;
	}

	.logo {
		height: 6em;
		padding: 1.5em;
		will-change: filter;
	}
	.logo:hover {
		filter: drop-shadow(0 0 2em #646cffaa);
	}
	.logo.svelte:hover {
		filter: drop-shadow(0 0 2em #ff3e00aa);
	}
	.read-the-docs {
		color: #888;
	}
</style>

```

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by pedaars** [comment]
i can do this

**Comment by nickytonline** [comment]
All yours @pedaars!
