### ISSUE TITLE
Create the Coin component

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#25]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

Design will come later, but for now, we have a basic stylized Coin component we need to add. A coin in Connect Four is the piece you drop in the Connect Four board.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Create the `src/lib/Coin.svelte` file and add this as the file contents.

```svelte
<script lang="ts">
	import type { Player } from '../types/GameTypes';

	export let player: Player;
</script>

<div>{player.color}</div>

<style>
	div {
		display: grid;
		place-items: center;
		font-size: 3rem;
		font-weight: bold;
		border-radius: 50%;
		border: dotted 4px #000;
		width: 100px;
		height: 100px;
	}
</style>
```

You will also need to create the `src/types/GameTypes.d.ts` file with the following contents.

```ts
export interface Player {
	color: 'R' | 'Y';
}
```

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by jocrah** [comment]
hi @nickytonline, would like to work on this :).
