### ISSUE TITLE
Create a favicon for the project

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#27]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

SvelteKit ships with a default favicon.png located at `static/favicon.png`. It's currently the SvelteKit logo. There are no designs for this, but a favicon related to the game of Connect Four would be great to have. Maybe the coin piece, but we leave it up to you to come up with a fun icon.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

A fun icon representative of the Connect Four game. Dimensions must be 128px x 128px

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by LoganArnett** [comment]
I can take a crack at this

**Comment by nickytonline** [comment]
Assigned it to you @LoganArnett!

**Comment by LoganArnett** [comment]
2 quick options but can work on something more if needed
#### More dynamic like the game
![favicon-connect-four-1](https://user-images.githubusercontent.com/8780547/194733611-be13b0b4-e5ef-49e1-9f77-6d57d4baa3ec.png)

#### Simple and clean
![favicon-connect-four-2](https://user-images.githubusercontent.com/8780547/194733621-406a9765-2a2b-4e84-946d-8485b682f90d.png)

**Comment by LoganArnett** [comment]
Will create a PR with the file once confirmed

**Comment by nickytonline** [comment]
I love this one @LoganArnett!

![favicon-connect-four-1](https://user-images.githubusercontent.com/8780547/194733611-be13b0b4-e5ef-49e1-9f77-6d57d4baa3ec.png)

Thoughts @Narigo @sadiejay?

**Comment by sadiejay** [comment]
Agreed @nickytonline 🙌🏾

**Comment by Narigo** [comment]
I like the board style more as well. I'd love to have a board that could actually be played, though 😅

Maybe something like this? (If the 4 is still visible in the small scales...)
![image](https://user-images.githubusercontent.com/1767865/194765799-24e23461-963b-4028-a60f-06a8d6f2cfde.png)

**Comment by nickytonline** [comment]
Actually one suggestion for my choice. Since there are only two game piece colours, could you make the yellow ones blue? Or maybe make them all blue and the current red ones could be yellow. Thoughts?

**Comment by LoganArnett** [comment]
Yea when I did the full 6x7 board it wasnt very visible as an actual favicon. I used the color layout I did for visibility and aesthetic but I can go to a full board if you want. And what are the 2 colors? I tried to have blue represent an empty square and red and yellow being pieces.

**Comment by LoganArnett** [comment]
@Narigo it is very difficult to see at 128x128 and true favicon display will be even smaller like:
<img width="39" alt="image" src="https://user-images.githubusercontent.com/8780547/194768032-1ace2978-1bf8-48d8-8726-536b6434687d.png">

**Comment by Narigo** [comment]
I'm okay with whatever you choose 👍
For the example, I used blue for empty spots as well. Red began and won in the example ;)

**Comment by nickytonline** [comment]
> @Narigo it is very difficult to see at 128x128 and true favicon display will be even smaller like:
> 
> <img width="39" alt="image" src="https://user-images.githubusercontent.com/8780547/194768032-1ace2978-1bf8-48d8-8726-536b6434687d.png">
> 
> 

Actually, it still looks good in @Narigo's example good even at 128 x 128, and I just noticed the red makes a 4. Just wondering how we could make the 4 pop more. I think from the classic game, the board was blue, so wondering if it could be a blue background, white for empty slots and keep the rest as is?

I also want to be mindful of your time, so if this is too much, just let us know.

**Comment by Narigo** [comment]
Maybe with a bit different colors and less space between them, it could pop out more? I don't feel it that much though.

![image](https://user-images.githubusercontent.com/1767865/194770010-4731c90a-f44d-45d2-9ead-a380065e335a.png)

Here would be an SVG to change colors etc. I've put it into square format:
![connect-4-board](https://user-images.githubusercontent.com/1767865/194770167-3dc25072-70ca-455a-9ccc-c8847eec02f3.svg)

**Comment by LoganArnett** [comment]
![favicon](https://user-images.githubusercontent.com/8780547/194780402-e32a22b0-c183-4d1b-9454-b84c4d1c8169.png)

**Comment by LoganArnett** [comment]
I tried to update for the favicon with colors that would make the 4 pop a little more by fading the white and yellow slightly, keeping the darker blue, and adding minimal shadow to the red pieces

**Comment by nickytonline** [comment]
Love it @LoganArnett! Thanks so much for doing this. I'll just let @sadiejay and @Narigo chime in again. Looking forward to seeing the new icon rolled out. 😎

**Comment by LoganArnett** [comment]
I created the PR but can update as needed
