### ISSUE TITLE
Add documentation to explain how to work in CodeSandbox

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#30]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

CodeSandbox is another great place to work in the browser when working on projects.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

Create a Section in the ReadME under the Gitpod section and call it `Development in CodeSandbox`. Ensure it's a level 2 heading, i.e. this is the markdown `## Development in CodeSandbox`.

There is no copy for this section, so use your judgement. Something along the lines of, you can work on the project in CodeSandbox...

There is existing [CodeSandbox documentation about working on a fork of a project](https://codesandbox.io/docs/learn/getting-started/open-source#forking-open-source-repositories), so incorporate that into the short resume of how to work on the project in CodeSandbox.

A link in the ReadME that takes you to the right spot in Codesandbox, would be even better. Less friction for someone looking to work in Codesandbox.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by jdwilkin4** [comment]
Hi @nickytonline ! 
I am interested in working on this 😄
