### ISSUE TITLE
Fix CI failing due to npm run lint failing in prebuild script

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#44]
**Describe the bug** A clear and concise description of what the bug is.

Great work from @jdwilkin4 in #43! Love those new docs! I approved and merged it on mobile not realizing that the build was failing due to a formatting issue.

@jdwilkin4 or anyone else, feel free to grab this.

To fix this, from the root of the project, run `npx prettier README.md --write`.

**To Reproduce** Steps to reproduce the behavior:

1. Run `npm run lint`
2. A warning about forgetting to run prettier on the ReadME appears

**Expected behavior** A clear and concise description of what you expected to
happen.

No formatting errors when running `npm run lint`

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by muckitymuck** [comment]
assign it to me please.
