### ISSUE TITLE
Remove the two coin pieces at bottom of the game page

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#51]
## Description

When we did the live stream with the initial work for the game, I had added two coin components at the bottom of the game page to show what they look like. These are no longer required and can be removed.

Remove the two coin components from https://github.com/nickytonline/connect-four/blob/main/src/routes/%2Bpage.svelte

```diff
<script>
	import Board from '../lib/Board.svelte';
	import Coin from '../lib/Coin.svelte';
</script>

<header>
	<h1>The beginnings of the classic Connect Four game.</h1>
</header>
<main>
	<h2>Welcome to SvelteKit</h2>
	<p>Visit <a href="https://kit.svelte.dev/">kit.svelte.dev</a> to read the documentation</p>
	<Board />
-	<Coin player={{ color: 'R' }} />
-	<Coin player={{ color: 'Y' }} />
</main>
Footer © 2022 GitHub, Inc. Footer navigation

<style>
	h1 {
		padding: 1rem;
		border: 2rem dotted blue;
	}
</style>
```

**Comment by vaishnav-mk** [comment]
Hi! Came across this due to the good first issues label. Is this still open? Seems like a pr was merged recently and I'm not sure if you're looking for anymore contributions regarding this

**Comment by nickytonline** [comment]
@vaishnav-mk its actually completed. Not sure why it's still open. I'm going to go ahead and close it.
