### ISSUE TITLE
App not showing right on Ubuntu 22

### ISSUE THREAD

**Issue by tamalchowdhury** [nickytonline/connect-four#64]
Is this app looking right or broken?

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/7252898/196906766-f9381281-938c-4dfc-98d2-dcb7c0f7c996.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.1 LTS
- Browser: Chrome
- Version 106

Same with latest Firefox.

**Comment by nickytonline** [comment]
@tamalchowdhury, it's a work in progress. That's how it currently looks. This was it initial pairing and debugging for the beginning of the app. It's not fully functional yet. #49 and #52 are open to fix up the UI.

This makes me think we should mention it's a work in progress in the ReadME.

**Comment by tamalchowdhury** [comment]
Okay, then it's cool. I am going to drop some code to help it get working.

**Comment by tamalchowdhury** [comment]
Closing the issue
