### ISSUE TITLE
Repeated line in README.md

### ISSUE THREAD

**Issue by muckitymuck** [nickytonline/connect-four#70]
**Describe the bug**

An extra line in README.md that can be removed.

"A web-based version of the classic game Connect Four."

**To Reproduce** 

1. Go to README.md

**Expected behavior** 

An Introduction that does not repeat.

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/6893378/198142259-b5ba1200-9c39-4135-b480-fec5c0bdb08a.png)

**Comment by muckitymuck** [comment]
Is it ok if I submit a PR to remove that line?

**Comment by nickytonline** [comment]
Good catch on the extra line @muckitymuck. I think that was my goof when I made some ReadME changes a while back. Mind just creating an issue as per the [contributing guide](https://github.com/nickytonline/connect-four/blob/main/CONTRIBUTING.md) for this and linking it to the pull request? Thanks!
