### ISSUE TITLE
warning  A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/connect-four#77]
**Describe the bug** A clear and concise description of what the bug is.

Fix the linting warning by making the interaction for dropping a coin in a column keyboard friendly.

**To Reproduce** Steps to reproduce the behavior:

1. Run `npm run lint`
2. The a11y lint warning appears

```
/Users/nicktaylor/dev/oss/connect-four/src/lib/Board.svelte
  33:3  warning  A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event  a11y-click-events-have-key-events
```

**Expected behavior** A clear and concise description of what you expected to
happen.

The lint warning

```
/Users/nicktaylor/dev/oss/connect-four/src/lib/Board.svelte
  33:3  warning  A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event  a11y-click-events-have-key-events
```

should no longer appear and a player is able to use the keyboard to add a coin to a column

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

To make this keyboard navigable, the board has to be able to receive focus and tabbing in the board should change columns. Consider focus states as well to indicate which column you're currently on.

**Comment by danieltott** [comment]
I'll take this one!
